apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: mysql
  namespace: fleet-local
spec:
  resources:
    - name: mysql
      path: ../mysql
  targets:
    - clusterSelector: {}  # This applies to all clusters

